### ISSUE TITLE
NYT US County Data Not Updating

### ISSUE THREAD

**Issue by ckingsbury** [kjhealy/covdata#10]
I installed the package via Drat, and am attempting to use the NYT county-level data with the following calls:

`library(covdata)`
`nytcovcounty`

While I get data, it appears to be current up through  9/15 only, and I can't get it to update beyond that. Following the breadcrumbs back to the NYT Github page, I find this (big CSV file) which appears to contain data through 9/30. It appears the URL might be different from the one the package is calling? 

https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv

**Comment by kjhealy** [comment]
Yes, you're right—the file had gotten big enough that the URL changed. Just pushed a fix.
