### ISSUE TITLE
More examples of elegant graphs which can be built with this data?

### ISSUE THREAD

**Issue by davidkane9** [kjhealy/covdata#7]
Thanks for creating such a useful package! Thanks, also, for including such a nice looking graph in the README. I seem to recall that earlier versions of the package had several more plots, all also beautiful. 

1) Is the code for those old plots available?

2) Do you have links/suggestion for how to use this data to make graphs like the ones students can see at places like the Economist or the Financial Times?

I plan on using this data for classroom exercises in September and it would be nice to have students build up some professional looking graphics step-by-step.

**Comment by kjhealy** [comment]
Hi David, 

Sorry I didn't see this issue till now. Code to draw many of the graphs you remember (and more besides) is available in the vignettes and on the package website: https://kjhealy.github.io/covdata. Look under the "Articles" menu item at the top of the page. E.g. https://kjhealy.github.io/covdata/articles/us-data.html

You can also find related worked examples using the `covdata` package under the visualization category on my blog: https://kieranhealy.org/categories/visualization/

**Comment by davidkane9** [comment]
Ah. Sorry. Missed that. Thanks!
