### ISSUE TITLE
Bad covus data for NC from covidtracking.com

### ISSUE THREAD

**Issue by coynedog** [kjhealy/covdata#8]
I hope this is an appropriate issue report, it is my first on GitHub.

The cumulative negative test count in covus decreases after August 11th. The incorrect numbers seem to be coming from  [The COVID Tracking Project.](https://covidtracking.com/data/state/north-carolina#historical)

<img width="552" alt="Screen Shot 2020-08-18 at 12 44 20 PM" src="https://user-images.githubusercontent.com/50178531/90542112-9fee0c00-e151-11ea-886f-5c8f04e2d294.png">

**Comment by kjhealy** [comment]
Hi @coynedog, thanks for the report. Totally appropriate. 

States and other reporting agencies periodically revise or update their counts, usually either by revising recent counts a few days or weeks later or, less often, by retrospectively changing the criteria for inclusion in the numbers reported. This gets reflected in the measures. Sometimes they _don't_ retroactively update them and errors sometimes stay in. As I say in the README, the data are provided as-is, which means further cleaning (or decisions about how to deal with anomalous counts, etc) might well be needed. Given the main purpose of the data (for teaching and maybe further analysis) I decided I didn't want to unilaterally make these corrections myself, especially as I generally don't have a consistent basis for making changes. Instead I'm providing the data as it's reported, with the understanding that it might have these sorts of issues.
