### ISSUE TITLE
Reinstalling gives an error

### ISSUE THREAD

**Issue by karthiktadepalli1** [kjhealy/covdata#9]
I installed `covdata` in July, and wanted to reinstall it to get the most updated data. However, reinstalling with `remotes::install_github("kjhealy/covdata")` errors out. I've copy-pasted the full message below.
```
✓  checking for file ‘/tmp/Rtmp08QQFe/remotes79a73922704/kjhealy-covdata-f3112f6/DESCRIPTION’ (343ms)
─  preparing ‘covdata’:
✓  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘covdata_0.4.4.tar.gz’
   
Installing package into ‘/home/karthiktadepalli1/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘covdata’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Killed
Error: Failed to install 'covdata' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp08QQFe/file79a75ed87c9/covdata_0.4.4.tar.gz’ had non-zero exit status
```
What could be causing this? I didn't have any problem the first time I installed `covdata`.

**Comment by kjhealy** [comment]
It's not clear why the install process was killed. If you try `remotes::install_github("kjhealy/covdata")` with the current version do you still have this issue?

**Comment by dhicks** [comment]
I'm experiencing the same problem on RStudio Cloud.  Installation is working fine on my Mac as well as on Travis.  

I cloned the repository to the RStudio Cloud instance, in case it was an issue communicating with GitHub.  (I've had that happen on RStudio Cloud in the recent past.)  Installation fails somewhere after creating the "locked" installation directory, which causes a prior error on subsequent attempts, so I'm passing the option to disable locking.  (I'm not entirely sure what "locking" does.)  Here's the call I'm using:  
```
remotes::install_local('covdata', 
                       build_manual = FALSE, 
                       build_vignettes = FALSE, 
                       force = TRUE,
                       INSTALL_opts = c('--no-lock'), 
                       verbose = TRUE)
```

The output is identical to the OP, modulo differences in the paths. 

Both RStudio Cloud and Travis are as current as possible.  R 4.0.2, remotes 2.2.0.  The covdata version is 0.4.6, and the most recent commit on the clone is f447b0f9ffb0920f639cdffc454e4f073f6d7463. 

I don't think I can drop a link to the RStudio Cloud instance here.  I can email it if you'd like to poke around there.

**Comment by dhicks** [comment]
Web searches aren't turning up many results with "killed" output from `install.packages()`.  But this thread suggests the possibility that it's a memory issue:  <https://community.rstudio.com/t/virtualenv-install-packages-spacy-killed-in-rstudio-cloud/25904/2>

Edit to add: The repository is about 750 MB, which might potentially run up against the 1 GB RAM limit on a (free) RStudio instance, if installation somehow required loading the whole repository into memory.  But the vast majority of that 750 MB is in `.git`.  Removing that took the total size of the repository down to 36 MB.  Which should be fine.

**Comment by dhicks** [comment]
Just to add to the strangeness:  This thread suggests that the `Killed` message is raised after the package has finished installing, because R runs out of memory doing the test-load: <https://community.rstudio.com/t/killed-error-during-installation-for-many-packages/24239/2>

I had not tried `library(covdata)` after getting the error message.  It turns out that call runs just fine, I can load the datasets in the usual way, etc.

**Comment by dhicks** [comment]
With further investigation, it seems highly likely that the problem (at least on RStudio Cloud) is with the test load of `google_mobility`, which is slightly over 1 GB once loaded.

**Comment by kjhealy** [comment]
Yeah looks like a memory issue. I'll have to think about what to do about the mobility data as it continues to expand in size.

**Comment by karthiktadepalli1** [comment]
For what it's worth, I was able to fix this issue by restarting the session and loading `devtools` into the namespace *before* any other packages, and then `devtools::install_github("kjhealy/covdata")` ran without a hitch. This is on local, not RStudio Cloud, so at least on my computer it didn't seem to be a memory issue.

**Comment by karthiktadepalli1** [comment]
As for the mobility data, one viable solution might be to replace the inbuilt dataset with a function that users can call to read the mobility data from the internet (it seems to have a [stable link](https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv)). Some cursory time tests on my machine suggest that `fread` from `data.table` takes 40 seconds, while `read_csv` takes 50 seconds, both of which seem reasonable.

**Comment by kjhealy** [comment]
I've moved the Google Mobility dataset out of the package (into a separate one), as I think it was the main reason things were choking. With any luck this'll fix the issue on RStudio cloud.
